"""
Django settings for qiu project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7#hr9s6u5o5++%-^@kjmkbkk8*ip#_g81uk(_do3gth@@)lz^!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['p.guiaihai.com','43.139.14.122','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "index.apps.IndexConfig",
    "article.apps.ArticleConfig",
    "weibo.apps.WeiboConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'qiu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'qiu.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ts_guiaihai',
        'USER': 'root',
        'PASSWORD': 'liao??1517',
        'HOST': '43.139.14.122',  # 如果数据库在本地
        'PORT': '3306',       # 默认 MySQL 端口
    },
    'book': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ts_guiaihai_book',
        'USER': 'root',
        'PASSWORD': 'liao??1517',
        'HOST': '43.139.14.122',  # 如果数据库在本地
        'PORT': '3306',       # 默认 MySQL 端口
    },
    'meiwen': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ts_guiaihai_meiwen',
        'USER': 'root',
        'PASSWORD': 'liao??1517',
        'HOST': '43.139.14.122',  # 如果数据库在本地
        'PORT': '3306',       # 默认 MySQL 端口
    },
    'gushi': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ts_guiaihai_gushi',
        'USER': 'root',
        'PASSWORD': 'liao??1517',
        'HOST': '43.139.14.122',  # 如果数据库在本地
        'PORT': '3306',       # 默认 MySQL 端口
    },
    'zuowen': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ts_guiaihai_zuowen',
        'USER': 'root',
        'PASSWORD': 'liao??1517',
        'HOST': '43.139.14.122',  # 如果数据库在本地
        'PORT': '3306',       # 默认 MySQL 端口
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'writable/cache'),  # 缓存文件存放的目录
    }
}

